services:
  cognitusbackend.api:
    image: ${DOCKER_REGISTRY-}cognitusbackendapi
    build:
      context: .
      dockerfile: CognitusBackend/Dockerfile
    environment:
      - KEY_OPENROUTER=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
    ports:
      - "5000:5000"
      - "5001:5001"
