services:
  cognitusbackend.api:
    image: ${DOCKER_REGISTRY-}cognitusbackendapi
    build:
      context: .
      dockerfile: CognitusBackend/Dockerfile
    environment:
      - KEY_OPENROUTER=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
    ports:
      - "5000:5000"
      - "5001:5001"
